###
POST {{name}}/quiz/create
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwicm9sZSI6IlJPTEVfVVNFUiIsImlzcyI6ImNvc3NjIiwiaWF0IjoxNjc1MzQxMjk0LCJleHAiOjE2NzUzNDQ4OTQsImF1ZCI6IjQwNjAwMzA2In0.Ux2pRBOVE_23P6AwkVG7NdcBvRK7NElNDGfh4gpc7tRVYT-U8XZSoJCX9oYTF6NQyUXdrFByfagf2BJYI3ZF1w
Content-Type: application/json

{
    "title": "test",
    "description": "test",
    "type": "1",
    "createdBy": "d36choi",
    "updatedBy": "d36choi",
    "tagId": "1"
}

###
