spring:
  config:
    activate:
      on-profile: local
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/cossc?createDatabaseIfNotExist=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true


  sql:
    init:
      mode: always
      schema-locations: classpath*:db/cossc/schema.sql
      data-locations: classpath*:db/cossc/data.sql
      platform: mysql

---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 30
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/cossc?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
  sql:
    init:
      mode: embedded
      schema-locations: classpath*:db/cossc/schema.sql
      data-locations: classpath*:db/cossc/data.sql
---
spring:
  profiles:
    group:
      "local": "local,secret"
      "prod": "prod,secret"