spring:
  config:
    activate:
      on-profile: local
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/cossc?createDatabaseIfNotExist=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  sql:
    init:
      mode: never
      schema-locations: classpath*:db/cossc/schema.sql
      data-locations: classpath*:db/cossc/data.sql
      platform: mysql
server:
  port: 8080

logging:
  level:
    org:
      springframework:
        web:
          filter: debug
---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 30
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/cossc?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


  sql:
    init:
      mode: embedded
      schema-locations: classpath*:db/cossc/schema.sql
      data-locations: classpath*:db/cossc/data.sql

logging:
  level:
    org:
      springframework:
        web:
          filter: debug
---
spring:
  config:
    activate:
      on-profile: test
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


  sql:
    init:
      mode: never
      schema-locations: classpath*:db/cossc/schema.sql
      data-locations: classpath*:db/cossc/data.sql
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
#    username: root
#    password: root
#    url: jdbc:tc:mysql/cossc?createDatabaseIfNotExist=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true


---
spring:
  profiles:
    group:
      "test": "test,secret"
      "local": "local,secret"
      "prod": "prod,secret"